# Стадия 1: збірка
FROM golang:1.24-alpine3.21 AS builder

WORKDIR /app
RUN apk add --no-cache mysql-client

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o main ./cmd/main.go

# Стадия 2: запуск
FROM alpine:3.21

WORKDIR /app
COPY --from=builder /app/main .
COPY --from=builder /usr/src/app/configs configs
COPY --from=builder /usr/bin/mysql /usr/bin/mysql

CMD ["./main"]
