FROM golang:1.24-alpine AS builder
LABEL "Project"="request-manager"
LABEL "Author"="Illia Kuchuk"

WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /main ./cmd/main.go

FROM alpine:latest
WORKDIR /root/

RUN apk add --no-cache \
    ca-certificates \
    tzdata \
    mariadb-client \
    bash

COPY --from=builder /main .
COPY --from=builder /usr/src/app/.env .env
COPY --from=builder /usr/src/app/configs configs

EXPOSE 8000
CMD ["./main"]