apiVersion: apps/v1
kind: Deployment
metadata:
  name: req-back
spec:
  selector:
    matchLabels:
      app: req-back
  template:
    metadata:
      labels:
        app: req-back
    spec:
      containers:
        - name: req-back
          image: zyzelq/req-back:local
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "req-db"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "123123"
            - name: DB_NAME
              value: "request_manager"

---
apiVersion: v1
kind: Service
metadata:
  name: req-back-service
spec:
  type: ClusterIP
  selector:
    app: req-back
  ports:
    - port: 8000
      targetPort: 8000
