apiVersion: apps/v1
kind: Deployment
metadata:
  name: req-back
spec:
  selector:
    matchLabels:
      app: req-back
  template:
    metadata:
      labels:
        app: req-back
    spec:
      containers:
        - name: req-back
          image: zyzelq/req-back:v13
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1" # 1 ядро
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: req-back
spec:
  type: NodePort
  selector:
    app: req-back
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
