FROM mysql:8.0.41-oraclelinux9

LABEL "Project"="request-manager"
LABEL "Author"="Illia Kuchuk"

ENV MYSQL_ROOT_PASSWORD="123123"
ENV MYSQL_DATABASE="request_manager"
EXPOSE 3308:3306
COPY db_backup.sql /docker-entrypoint-initdb.d/
