version: "3.8"

services:
  app:
    build: ./request-manager-api
    container_name: req-back
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=req-db
      - DB_PORT=3306 # Используем правильный внутренний порт
      - DB_USER=root
      - DB_PASSWORD=123123
      - DB_NAME=request_manager
    networks:
      - my-network

  db:
    build: ./request-manager-database
    container_name: req-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=request_manager
    ports:
      - "3308:3306" # Внешний порт 3308 для доступа из-за пределов Docker
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  frontend:
    build: ./request-manager-ui
    container_name: req-front
    ports:
      - "5173:5173" # Открываем порт Vite
    depends_on:
      - app
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge
