FROM node:20-alpine

LABEL "Project"="request-manager"
LABEL "Author"="Illia Kuchuk"

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "--open=false"]