apiVersion: apps/v1
kind: Deployment
metadata:
  name: req-front
spec:
  selector:
    matchLabels:
      app: req-front
  template:
    metadata:
      labels:
        app: req-front
    spec:
      containers:
        - name: req-front
          image: zyzelq/req-front:cluster2
          ports:
            - containerPort: 5173
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: req-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer
