apiVersion: apps/v1
kind: Deployment
metadata:
  name: req-front
spec:
  selector:
    matchLabels:
      app: req-front
  template:
    metadata:
      labels:
        app: req-front
    spec:
      containers:
        - name: req-front
          image: zyzelq/req-front:v5
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1" # 1 ядро
              memory: "1Gi"
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: req-front-service
spec:
  type: NodePort # ВАЖНО!
  selector:
    app: req-front
  ports:
    - port: 80
      targetPort: 5173
      nodePort: 30000 # Четко укажи нужный порт тут

