apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: req-front # <- Должен совпадать с лейблом в Deployment!
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: NodePort # <- Лучше для локального кластера (LoadBalancer не работает без доп. настройки)
