name: req actions

on: workflow_dispatch

env:
  AWS_REGION: us-east-1
  REPOSITORY_FRONTEND: e-requestcontrol-frontend
  REPOSITORY_BACKEND: e-requestcontrol-backend
  REPOSITORY_DB: e-requestcontrol-db
  EKS_CLUSTER: e-requestcontrol-eks

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with: 
          go-version: '1.22' 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Install Node dependencies
        working-directory: request-manager-ui
        run: npm install
# Setup java 11 to be default (sonar-scanner requirement as of 5.x)
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '11'

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      - name: Debug Sonar variables
        run: |
          echo "SONAR_ORGANIZATION:${{ secrets.SONAR_ORGANIZATION }}"
          echo "SONAR_PROJECT_KEY:${{ secrets.SONAR_PROJECT_KEY }}"
          echo "SONAR_URL:${{ secrets.SONAR_URL }}"

      # Start scanning
      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=request-manager-api,request-manager-ui \
            -Dsonar.language=go \
            -Dsonar.inclusions=**/*.go,**/*.js,**/*.vue \
            -Dsonar.exclusions=**/node_modules/**,**/vendor/**

  BUILD_AND_PUBLISH:   
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Push Frontend
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.REGISTRY }}
          repo: ${{ env.REPOSITORY_FRONTEND }}
          region: ${{ env.AWS_REGION }}
          tags: latest,${{ github.run_number }}
          dockerfile: request-manager-ui/dockerfile
          context: ./request-manager-ui

      - name: Push Backend
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.REGISTRY }}
          repo: ${{ env.REPOSITORY_BACKEND }}
          region: ${{ env.AWS_REGION }}
          tags: latest,${{ github.run_number }}
          dockerfile: request-manager-api/dockerfile
          context: ./request-manager-api

      - name: Push DB
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.REGISTRY }}
          repo: ${{ env.REPOSITORY_DB }}
          region: ${{ env.AWS_REGION }}
          tags: latest,${{ github.run_number }}
          dockerfile: request-manager-database/dockerfile
          context: ./request-manager-database

      - name: Configure AWS credentials for cleanup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: delete old ecr
        run: |
          REPO_NAMES=("${{ env.REPOSITORY_FRONTEND }}" "${{ env.REPOSITORY_BACKEND }}" "${{ env.REPOSITORY_DB }}")
          for repo in "${REPO_NAMES[@]}"; do
            echo "Cleaning up $repo"
            tags=$(aws ecr describe-images \
              --repository-name "$repo" \
              --region "${{ env.AWS_REGION }}" \
              --query 'imageDetails[*].imageTags' \
              --output json | jq -r '.[][]' | grep -v latest | grep -E '^[0-9]+$' | sort -n)
            echo "All numeric tags: $tags"
            tags_to_keep=$(echo "$tags" | tail -n 2)
            tags_to_delete=$(comm -23 <(echo "$tags" | sort -n) <(echo "$tags_to_keep" | sort -n))
            for tag in $tags_to_delete; do
              echo "Deleting $repo:$tag"
              aws ecr batch-delete-image \
                --repository-name "$repo" \
                --region "${{ env.AWS_REGION }}" \
                --image-ids imageTag="$tag"
            done
          done

  DeployToEKS:
    needs: BUILD_AND_PUBLISH
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Kube config file
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Print config file
        run: cat ~/.kube/config

      - name: Create Kubernetes Secret
        run: |
          kubectl create secret generic db-secrets \
            --from-literal=root-password="${{ secrets.DB_ROOT_PASSWORD }}" \
            --from-literal=db-name="${{ secrets.DB_NAME }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Install Cert-Manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
          echo "Waiting for cert-manager pods to be ready..."
          kubectl rollout status deployment/cert-manager -n cert-manager --timeout=120s || true
          kubectl rollout status deployment/cert-manager-webhook -n cert-manager --timeout=120s || true
          kubectl rollout status deployment/cert-manager-cainjector -n cert-manager --timeout=120s || true

      - name: Apply ClusterIssuer
        run: |
          kubectl apply -f req-helm/cluster-issuer.yaml

      - name: Deploy Prometheus and Loki stack
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

          helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
            --namespace monitoring --create-namespace \
            --set grafana.enabled=false \
            --set grafana.image.tag=10.2.3

          helm upgrade --install loki grafana/loki-stack --namespace monitoring \
            --values req-helm/values_cloud.yaml

      - name: Login to ECR
        run: |
          kubectl delete secret regcred --ignore-not-found
          kubectl create secret docker-registry regcred \
            --docker-server=${{ secrets.REGISTRY }} \
            --docker-username=AWS \
            --docker-password=$(aws ecr get-login-password)

      - name: Deploy Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          cluster-name: ${{ env.EKS_CLUSTER }}
          chart-path: ./req-helm
          namespace: default
          config-files: req-helm/values_cloud.yaml
          name: req-helm    

      - name: Configure MySQL root access
        run: |
          kubectl wait --for=condition=ready pod -l app=req-db --timeout=300s
          
          DB_POD=$(kubectl get pods -l app=req-db -o jsonpath='{.items[0].metadata.name}')
          
          kubectl exec $DB_POD -- \
            mysql -uroot -p"${{ secrets.DB_ROOT_PASSWORD }}" \
            -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '${{ secrets.DB_ROOT_PASSWORD }}'; FLUSH PRIVILEGES;"
